package cn.njcit.mapper.model;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_login_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String accountLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_password
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String accountPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer accountStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_owner
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer accountOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_owner_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer accountOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_id
     *
     * @return the value of account.account_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_id
     *
     * @param accountId the value for account.account_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_login_name
     *
     * @return the value of account.account_login_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getAccountLoginName() {
        return accountLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_login_name
     *
     * @param accountLoginName the value for account.account_login_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountLoginName(String accountLoginName) {
        this.accountLoginName = accountLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_password
     *
     * @return the value of account.account_password
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_password
     *
     * @param accountPassword the value for account.account_password
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_status
     *
     * @return the value of account.account_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_status
     *
     * @param accountStatus the value for account.account_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_owner
     *
     * @return the value of account.account_owner
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getAccountOwner() {
        return accountOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_owner
     *
     * @param accountOwner the value for account.account_owner
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountOwner(Integer accountOwner) {
        this.accountOwner = accountOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_owner_id
     *
     * @return the value of account.account_owner_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getAccountOwnerId() {
        return accountOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_owner_id
     *
     * @param accountOwnerId the value for account.account_owner_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountOwnerId(Integer accountOwnerId) {
        this.accountOwnerId = accountOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_time
     *
     * @return the value of account.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_time
     *
     * @param createTime the value for account.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.update_time
     *
     * @return the value of account.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.update_time
     *
     * @param updateTime the value for account.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}