package cn.njcit.mapper.model;

import java.util.Date;

public class Groups {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_no
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String groupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.group_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer groupStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_id
     *
     * @return the value of groups.group_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_id
     *
     * @param groupId the value for groups.group_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_no
     *
     * @return the value of groups.group_no
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_no
     *
     * @param groupNo the value for groups.group_no
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_name
     *
     * @return the value of groups.group_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_name
     *
     * @param groupName the value for groups.group_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.group_status
     *
     * @return the value of groups.group_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getGroupStatus() {
        return groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.group_status
     *
     * @param groupStatus the value for groups.group_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setGroupStatus(Integer groupStatus) {
        this.groupStatus = groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.create_time
     *
     * @return the value of groups.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.create_time
     *
     * @param createTime the value for groups.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.update_time
     *
     * @return the value of groups.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.update_time
     *
     * @param updateTime the value for groups.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}