package cn.njcit.mapper.model;

public class SchoolRegister {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_register.id
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_register.user_name
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_register.school
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_register.phone
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_register.id
     *
     * @return the value of school_register.id
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_register.id
     *
     * @param id the value for school_register.id
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_register.user_name
     *
     * @return the value of school_register.user_name
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_register.user_name
     *
     * @param userName the value for school_register.user_name
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_register.school
     *
     * @return the value of school_register.school
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_register.school
     *
     * @param school the value for school_register.school
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_register.phone
     *
     * @return the value of school_register.phone
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_register.phone
     *
     * @param phone the value for school_register.phone
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}