package cn.njcit.mapper.model;

import java.util.Date;

public class Specialty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.specialty_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer specialtyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.specialty_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String specialtyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.department_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.specialty_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer specialtyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialty_id
     *
     * @return the value of specialty.specialty_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialty_id
     *
     * @param specialtyId the value for specialty.specialty_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialty_name
     *
     * @return the value of specialty.specialty_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getSpecialtyName() {
        return specialtyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialty_name
     *
     * @param specialtyName the value for specialty.specialty_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setSpecialtyName(String specialtyName) {
        this.specialtyName = specialtyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.department_id
     *
     * @return the value of specialty.department_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.department_id
     *
     * @param departmentId the value for specialty.department_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialty_status
     *
     * @return the value of specialty.specialty_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getSpecialtyStatus() {
        return specialtyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialty_status
     *
     * @param specialtyStatus the value for specialty.specialty_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setSpecialtyStatus(Integer specialtyStatus) {
        this.specialtyStatus = specialtyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.create_time
     *
     * @return the value of specialty.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.create_time
     *
     * @param createTime the value for specialty.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.update_time
     *
     * @return the value of specialty.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.update_time
     *
     * @param updateTime the value for specialty.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}