package cn.njcit.mapper.model;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_no
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.group_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_specialty_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer studentSpecialtyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_grade
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer studentGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer studentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_phone
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String studentPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_email
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String studentEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_QQ
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String studentQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_no
     *
     * @return the value of student.student_no
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_no
     *
     * @param studentNo the value for student.student_no
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.group_id
     *
     * @return the value of student.group_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.group_id
     *
     * @param groupId the value for student.group_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_specialty_id
     *
     * @return the value of student.student_specialty_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getStudentSpecialtyId() {
        return studentSpecialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_specialty_id
     *
     * @param studentSpecialtyId the value for student.student_specialty_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentSpecialtyId(Integer studentSpecialtyId) {
        this.studentSpecialtyId = studentSpecialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_grade
     *
     * @return the value of student.student_grade
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getStudentGrade() {
        return studentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_grade
     *
     * @param studentGrade the value for student.student_grade
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentGrade(Integer studentGrade) {
        this.studentGrade = studentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_status
     *
     * @return the value of student.student_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getStudentStatus() {
        return studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_status
     *
     * @param studentStatus the value for student.student_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentStatus(Integer studentStatus) {
        this.studentStatus = studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_phone
     *
     * @return the value of student.student_phone
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_phone
     *
     * @param studentPhone the value for student.student_phone
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_email
     *
     * @return the value of student.student_email
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getStudentEmail() {
        return studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_email
     *
     * @param studentEmail the value for student.student_email
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_QQ
     *
     * @return the value of student.student_QQ
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getStudentQq() {
        return studentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_QQ
     *
     * @param studentQq the value for student.student_QQ
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setStudentQq(String studentQq) {
        this.studentQq = studentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_time
     *
     * @return the value of student.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_time
     *
     * @param createTime the value for student.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_time
     *
     * @return the value of student.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_time
     *
     * @param updateTime the value for student.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}