package cn.njcit.mapper.model;

import java.util.Date;

public class VerifyCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.code_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String codeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.code_content
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private String codeContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.code_action
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer codeAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.code_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer codeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.account_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.code_id
     *
     * @return the value of verify_code.code_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.code_id
     *
     * @param codeId the value for verify_code.code_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.code_content
     *
     * @return the value of verify_code.code_content
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public String getCodeContent() {
        return codeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.code_content
     *
     * @param codeContent the value for verify_code.code_content
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCodeContent(String codeContent) {
        this.codeContent = codeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.code_action
     *
     * @return the value of verify_code.code_action
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getCodeAction() {
        return codeAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.code_action
     *
     * @param codeAction the value for verify_code.code_action
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCodeAction(Integer codeAction) {
        this.codeAction = codeAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.code_status
     *
     * @return the value of verify_code.code_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getCodeStatus() {
        return codeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.code_status
     *
     * @param codeStatus the value for verify_code.code_status
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCodeStatus(Integer codeStatus) {
        this.codeStatus = codeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.account_id
     *
     * @return the value of verify_code.account_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.account_id
     *
     * @param accountId the value for verify_code.account_id
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.create_time
     *
     * @return the value of verify_code.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.create_time
     *
     * @param createTime the value for verify_code.create_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.update_time
     *
     * @return the value of verify_code.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.update_time
     *
     * @param updateTime the value for verify_code.update_time
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}