package cn.njcit.dao;

import cn.njcit.mapper.model.SchoolRegister;
import cn.njcit.mapper.model.SchoolRegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int countByExample(SchoolRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int deleteByExample(SchoolRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int insert(SchoolRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int insertSelective(SchoolRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    List<SchoolRegister> selectByExample(SchoolRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    SchoolRegister selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") SchoolRegister record, @Param("example") SchoolRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int updateByExample(@Param("record") SchoolRegister record, @Param("example") SchoolRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int updateByPrimaryKeySelective(SchoolRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_register
     *
     * @mbggenerated Tue Jan 16 21:20:34 CST 2018
     */
    int updateByPrimaryKey(SchoolRegister record);
}