package cn.njcit.dao;

import cn.njcit.mapper.model.VerifyCode;
import cn.njcit.mapper.model.VerifyCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerifyCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int countByExample(VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int deleteByExample(VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int deleteByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int insert(VerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int insertSelective(VerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    List<VerifyCode> selectByExample(VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    VerifyCode selectByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") VerifyCode record, @Param("example") VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int updateByExample(@Param("record") VerifyCode record, @Param("example") VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int updateByPrimaryKeySelective(VerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Sun Jan 21 01:25:58 CST 2018
     */
    int updateByPrimaryKey(VerifyCode record);
}